"""Render the committed evidence atlas as a browsable Markdown summary.

``data/derived/evidence_atlas.csv`` is the outward-facing artifact, but a raw
CSV is not a comfortable way for a community member to browse ten rows of
prose and figures. This module renders every committed atlas column into one
Markdown section per construct, in the same B1-through-B10 order as the CSV.

No new content is authored here: every cell is copied verbatim from
``evidence_atlas.csv``, so this file can never disagree with the atlas it
summarizes. See :mod:`labauto_observatory.atlas` for how the atlas itself is
built, and ``docs/evidence-atlas.md`` for what a row means and what it does
not support.
"""

from __future__ import annotations

from pathlib import Path

from .atlas import ATLAS_RELATIVE
from .io import normalised_newlines, read_csv, read_text_lf

SUMMARY_RELATIVE = "docs/generated/evidence_atlas_summary.md"

GENERATED_NOTICE = (
    "<!-- Generated by `scripts/build_atlas_summary.py` from "
    f"`{ATLAS_RELATIVE}`. Do not hand-edit; `make validate` checks for drift. -->"
)

TITLE = "# Evidence atlas summary"

INTRO = """This page is a generated, browsable rendering of every row in
[`{atlas}`]({atlas_github}). It exists so a reader can scan all ten
constructs without opening a spreadsheet. For what a row means, how to trace
it back to quotes, cases, and metrics, and what it does not support, read
[Evidence atlas](../evidence-atlas.md) first.

Regenerate with `make atlas-summary` (also run as part of `make derived`), or
directly with `uv run python scripts/build_atlas_summary.py`.""".format(
    atlas=ATLAS_RELATIVE,
    atlas_github=(
        f"https://github.com/fraware/lab-automation-observatory/blob/main/{ATLAS_RELATIVE}"
    ),
)

# One (label, atlas column) pair per rendered field, in display order. Keeping
# this list separate from `HEADER` in `atlas.py` lets the two files order
# columns differently without one silently dropping a field the other added.
FIELDS: tuple[tuple[str, str], ...] = (
    ("Analytical layer", "Analytical layer"),
    ("Direct-support threads", "Direct-support threads"),
    ("Primary-code threads", "Primary-code threads"),
    ("Bounded quantitative result", "Bounded quantitative result"),
    ("Evidence maturity", "Evidence maturity"),
    ("Pilot interpretation", "Pilot interpretation"),
    ("Strongest descriptive relationship", "Strongest descriptive relationship"),
    ("Illustrative quotation", "Short anonymized quotation"),
    ("Quotation source", "Quotation source"),
    ("Retained counterexample", "Retained counterexample"),
    ("Key sources", "Key sources"),
)


def _section(row: dict[str, str]) -> str:
    heading = f"## {row['Code']} -- {row['Bottleneck']}"
    lines = [heading, ""]
    for label, column in FIELDS:
        value = row[column].strip() or "*None recorded in this pilot.*"
        lines.append(f"- **{label}:** {value}")
    return "\n".join(lines)


def render_atlas_summary(root: str | Path) -> str:
    """Render the Markdown summary exactly as it is committed."""

    rows = read_csv(Path(root) / ATLAS_RELATIVE)
    sections = "\n\n".join(_section(row) for row in rows)
    body = "\n\n".join([GENERATED_NOTICE, TITLE, INTRO, sections])
    return body + "\n"


def write_atlas_summary(root: str | Path) -> Path:
    """Write the regenerated Markdown summary and return its path."""

    destination = Path(root) / SUMMARY_RELATIVE
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_atlas_summary(root), encoding="utf-8", newline="")
    return destination


def atlas_summary_drift(root: str | Path) -> list[str]:
    """Report whether the committed summary still matches the atlas CSV."""

    destination = Path(root) / SUMMARY_RELATIVE
    if not destination.is_file():
        return [f"{SUMMARY_RELATIVE} is missing; run `make atlas-summary`"]
    if read_text_lf(destination) != normalised_newlines(render_atlas_summary(root)):
        return [f"{SUMMARY_RELATIVE} has drifted from {ATLAS_RELATIVE}; run `make atlas-summary`"]
    return []
